'use client';
import {useEffect,useState} from 'react';
import type {User} from '@supabase/supabase-js';
import {getSupabaseClient} from '@/lib/supabase';
import {inviteCodeFromHash,normalizeClassCode,validClassCode} from '@/lib/class-invites';
export default function AccountClasses({user,username}:{user:User;username:string}){
 const [code,setCode]=useState(''),[name,setName]=useState(username),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [members,setMembers]=useState<{class_id:string;display_name:string;share_comprehension:boolean}[]>([]);
 useEffect(()=>{let active=true;const client=getSupabaseClient();setCode(inviteCodeFromHash(window.location.hash)||String(user.user_metadata?.pending_class_code??''));setName(username);setConsent(false);setMembers([]);
 const load=async()=>{if(!client)return;const {data,error}=await client.from('learning_class_members').select('class_id,display_name,share_comprehension').eq('user_id',user.id);if(!active)return;if(error)setMessage('Could not load your classes. You can retry from the classroom page.');else setMembers(data??[]);};void load();window.addEventListener('cursos-class-membership-change',load);return()=>{active=false;window.removeEventListener('cursos-class-membership-change',load);};},[user.id,username]);
 async function join(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy||!consent||!validClassCode(code)||!name.trim())return;const client=getSupabaseClient();if(!client)return;setBusy(true);setMessage('');try{const {error}=await client.rpc('join_learning_class',{code:normalizeClassCode(code),learner_name:name.trim()});if(error)throw error;setMessage('Joined your class. Reading/listening comprehension stays private until you enable it in classroom settings.');setCode('');setConsent(false);window.history.replaceState(null,'',window.location.pathname+window.location.search+'#account');window.dispatchEvent(new Event('cursos-class-membership-change'));if(user.user_metadata?.pending_class_code)await client.auth.updateUser({data:{pending_class_code:null}});}catch{setMessage('Could not join. Check the class code with your teacher and try again. Your account is unchanged.');}finally{setBusy(false);}}
 return <section className="account-classes"><h3>My classes</h3><p>Enter the invite code from your teacher. Your course and vocabulary stay in your existing account.</p>{members.map(m=><p key={m.class_id}>Joined as <strong>{m.display_name}</strong> · comprehension sharing {m.share_comprehension?'on':'off'}</p>)}<form className="account-form" onSubmit={join}><label>Class code<input value={code} onChange={e=>{setCode(e.target.value);setConsent(false);}} maxLength={48} placeholder="Paste your class invite code" autoCapitalize="none" autoCorrect="off" required/></label><label>Name shown to your teacher<input value={name} onChange={e=>setName(e.target.value)} maxLength={80} required placeholder="Name or class alias"/></label><label className="class-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/>I agree to share my vocabulary practice counts and separate text, audio, and pattern recall results with this class’s owner. My answers and private notes are not shared.</label><button className="primary" disabled={busy||!consent||!validClassCode(code)||!name.trim()}>{busy?'Joining…':'Join class'}</button></form>{message&&<p role="status">{message}</p>}<a href="/classroom">Manage classes, comprehension sharing, or leave a class ↗</a></section>;
}
