import {comprehensionSummary,type ComprehensionEvidence} from '@/lib/student-report';
export default function ComprehensionReport({events,modality,detailed=false}:{events:ComprehensionEvidence[];modality:'reading'|'listening';detailed?:boolean}){
 const s=comprehensionSummary(events,modality),label=modality==='reading'?'Reading comprehension':'Listening comprehension';
 return <section className="report-panel"><div className="report-panel-heading"><h3>{label}</h3><span>{s.all.length} attempts</span></div><p className="comprehension-score">{s.score??'—'}{s.score!==null&&<small> / 100</small>}</p><p className="score-caption">{s.ai.length} AI-graded attempts · practice score</p>
 {s.all.length===0?<div className="empty-evidence">No {modality} evidence in this reporting period.</div>:<>
 {s.dimensions.map(d=><div className="dimension-row" key={d.type}><div><span>{d.label}</span><strong>{d.score===null?'Not tested':d.score+'%'}</strong></div><div className="insight-meter"><i style={{width:(d.score??0)+'%'}}/></div><small>{d.count} graded questions</small></div>)}
 {modality==='listening'?<div className="support-metrics"><div>Full report: one listen<strong>{s.firstListenScore===null?'—':s.firstListenScore+'%'}</strong>{s.firstListenCount} AI-graded attempts</div><div>Full report: supported<strong>{s.assistedScore===null?'—':s.assistedScore+'%'}</strong>{s.assistedCount} AI-graded attempts</div></div>:<div className="support-metrics"><div>Recorded reading time<strong>{s.all.some(e=>e.duration_ms!==null)?Math.round(s.all.reduce((n,e)=>n+(e.duration_ms??0),0)/60000)+' min':'—'}</strong>Across this period</div><div>Rereads recorded<strong>{s.all.some(e=>e.rereads!==null)?s.all.reduce((n,e)=>n+(e.rereads??0),0):'—'}</strong>Not a comprehension score</div></div>}
 <p className="evidence-note">Self-rated: {s.self.length} attempts{s.selfScore!==null?' · '+s.selfScore+'% average':''}. Excluded from AI averages and question-type results. {s.all.filter(e=>e.grading_mode==='unknown').length>0?'Some older attempts have no grading method recorded.':''}</p>
 {s.ai.length<3&&<p className="evidence-note">Limited evidence. Use more than one passage before drawing conclusions.</p>}</>}
 {detailed&&s.all.length>0&&<div className="history-wrap"><table><caption>Recent {modality} attempts · UTC</caption><thead><tr><th>Date</th><th>Score</th><th>Grading / mode</th><th>Support / time</th><th>Questions graded</th></tr></thead><tbody>{[...s.all].sort((a,b)=>b.attempted_at.localeCompare(a.attempted_at)).map(e=><tr key={e.id}><td>{new Date(e.attempted_at).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'UTC'})}</td><td>{e.score===null?'—':e.score+'%'}</td><td>{e.grading_mode==='ai'?'AI':e.grading_mode==='self'?'Self-rated':'Unknown'} · {e.practice_mode??'unknown'}</td><td>{modality==='reading'?(e.duration_ms===null?'Time unknown':Math.round(e.duration_ms/60000)+' min')+' · '+(e.rereads??'—')+' rereads':(e.listens??'—')+' listens · '+(e.transcript===null?'transcript unknown':e.transcript?'transcript used':'no transcript')}</td><td>{e.grading_mode==='ai'?e.questions.length:'—'}</td></tr>)}</tbody></table></div>}
 <p className="evidence-note">AI grading is advisory, not an official ILR assessment. Full-report listening comparisons exclude sentence-gist practice. Only recorded support is measured; external aids cannot be detected. Question types with no scored answers remain “Not tested.”</p></section>;
}
