'use client';
import {evidenceAction,type AssessmentRow,type GenerationQualityReport,type InterventionReport,type PilotEventReport} from '@/lib/pilot-report';

export default function PilotEvidence({report,quality,interventions,assessments,period,onPeriod,onCapture,busy}:{report:PilotEventReport|null;quality:GenerationQualityReport|null;interventions:InterventionReport[];assessments:AssessmentRow[];period:7|30|0;onPeriod:(period:7|30|0)=>void;onCapture:(period:'baseline'|'midpoint'|'endline')=>void;busy:boolean}){
 const assessed=new Set(assessments.map(row=>row.period));
 return <section className="pilot-evidence" id="pilot-evidence"><div className="report-section-title"><div><h2>Pilot evidence</h2><p>Attributable activity across Cursos, Synaptx, and Asl. Associations are descriptive, not causal.</p></div><label>Evidence window<select value={period} onChange={event=>onPeriod(Number(event.target.value) as 7|30|0)}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={0}>Course to date</option></select></label></div>
 <div className="assessment-actions"><span>Freeze a comparison point:</span>{(['baseline','midpoint','endline'] as const).map(item=><button key={item} disabled={busy} onClick={()=>onCapture(item)}>{assessed.has(item)?`Refresh ${item}`:`Capture ${item}`}</button>)}</div>
 {quality&&<section className="report-panel"><div className="report-panel-heading"><h3>Generated-practice reliability</h3><span>Consented activity only</span></div><div className="insight-summary"><div><span>Exercises attempted</span><strong>{quality.total}</strong></div><div><span>Passed QA</span><strong>{quality.learner_visible}</strong></div><div><span>Success rate</span><strong>{quality.success_rate===null?'—':`${quality.success_rate}%`}</strong></div><div><span>Generation latency</span><strong>{quality.p50_latency_ms===null?'—':`${(quality.p50_latency_ms/1000).toFixed(1)}s p50`}</strong><small>{quality.p95_latency_ms===null?'No measured latency':`${(quality.p95_latency_ms/1000).toFixed(1)}s p95`}</small></div></div>{quality.by_modality.length?<div className="quality-breakdown">{quality.by_modality.map((item,index)=><p key={`${item.modality}-${item.source_kind}-${item.register}-${index}`}><strong>{item.modality} · {item.source_kind??'unspecified'} · {item.register??'unspecified'}</strong>: {item.learner_visible}/{item.total} passed{item.p95_latency_ms===null?'':` · ${(item.p95_latency_ms/1000).toFixed(1)}s p95`}</p>)}</div>:<p className="empty-evidence">No generated-practice telemetry is available for this window.</p>}</section>}
 {!report?<p className="empty-evidence">No cross-product pilot evidence is available yet.</p>:<><div className="insight-summary"><div><span>Consented learners</span><strong>{report.learners.length}</strong></div><div><span>Suite events</span><strong>{report.learners.reduce((sum,row)=>sum+Number(row.attempts||0),0)}</strong></div><div><span>Interventions</span><strong>{interventions.reduce((sum,row)=>sum+Number(row.interventions||0),0)}</strong></div><div><span>Assessment snapshots</span><strong>{assessments.length}</strong></div></div>
 <div className="overview-charts"><section className="report-panel"><div className="report-panel-heading"><h3>Observed bottlenecks</h3><span>Minimum 3 events</span></div>{report.bottlenecks.length?report.bottlenecks.slice(0,8).map((item,index)=><div className="focus-row" key={`${item.product}-${item.skill}-${item.linguistic_concept}-${index}`}><strong>{item.product} · {item.skill??'exploration'} · {item.linguistic_concept??'uncategorized'}</strong><p>{item.accuracy===null?'Unscored':`${item.accuracy}% correct`} across {item.attempts} events{item.average_response_ms?` · ${Math.round(item.average_response_ms/100)/10}s average`:''}. {evidenceAction(item)}</p></div>):<p className="empty-evidence">Not enough repeated evidence to identify a bottleneck.</p>}</section>
 <section className="report-panel"><div className="report-panel-heading"><h3>After an intervention</h3><span>Observed before / after</span></div>{interventions.length?interventions.slice(0,8).map((item,index)=><div className="focus-row" key={`${item.linguistic_concept}-${index}`}><strong>{item.linguistic_concept??'Uncategorized concept'}</strong><p>{item.interventions} intervention{item.interventions===1?'':'s'} · accuracy {item.pre_accuracy??'—'}% → {item.post_accuracy??'—'}% · response {item.pre_latency_ms??'—'}ms → {item.post_latency_ms??'—'}ms. This does not establish that the intervention caused the change.</p></div>):<p className="empty-evidence">No intervention has both surrounding practice evidence and consent yet.</p>}</section></div></>}
 </section>;
}
