'use client';
import {useState} from 'react';
import {accuracy,evidenceAdvice,skillNames,skillTrend,mean,type StudentReport} from '@/lib/student-report';
import ComprehensionReport from './ComprehensionReport';
import ReportChart from './ReportChart';
export default function StudentBreakdown({student,onClose}:{student:StudentReport;onClose?:()=>void}){
 const [view,setView]=useState('overview'),events=student.comprehension??[],days=(student.daily??[]).map(d=>d.day);
 return <section className="student-breakdown" aria-label={student.display_name+' student breakdown'}>
 <header><div><p>INDIVIDUAL REPORT</p><h2>{student.display_name}</h2></div><div className="report-actions"><button onClick={()=>window.print()}>Print report ↗</button>{onClose&&<button onClick={onClose}>Close</button>}</div></header>
 <div className="student-metrics"><p><strong>{student.reviews}</strong>Vocabulary reviews</p><p><strong>{student.comprehension_shared?events.length:'—'}</strong>Comprehension attempts</p><p><strong>{student.unique_words??'—'}</strong>Distinct words reviewed</p></div>
 <div className="report-tabs" role="tablist" aria-label="Report section">{['overview','reading','listening','vocabulary'].map(v=><button key={v} role="tab" id={'tab-'+v} aria-selected={view===v} aria-controls="learner-panel" tabIndex={view===v?0:-1} onClick={()=>setView(v)} onKeyDown={e=>{const tabs=['overview','reading','listening','vocabulary'];if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=tabs[(tabs.indexOf(v)+(e.key==='ArrowRight'?1:3))%4];setView(next);document.getElementById('tab-'+next)?.focus();}}}>{v[0].toUpperCase()+v.slice(1)}</button>)}</div>
 <div role="tabpanel" id="learner-panel" aria-labelledby={'tab-'+view}>
 {view!=='vocabulary'&&!student.comprehension_shared?<p className="empty-evidence">Comprehension results are not shared. This learner can opt in from their classroom membership settings. Vocabulary sharing is unchanged.</p>:view==='overview'?<><div className="comprehension-grid"><ComprehensionReport events={events} modality="reading"/><ComprehensionReport events={events} modality="listening"/></div><section className="report-panel" style={{marginTop:20}}><div className="report-panel-heading"><h3>Individual comprehension trend</h3><span>AI-graded only</span></div><ReportChart days={days} series={(['reading','listening'] as const).map(modality=>({label:modality==='reading'?'Reading':'Listening',dashed:modality==='listening',values:days.map(day=>mean(events.filter(e=>e.modality===modality&&e.grading_mode==='ai'&&e.attempted_at.slice(0,10)===day).map(e=>e.score)))}))} label={student.display_name+' daily comprehension scores'}/></section></>:view==='reading'||view==='listening'?<ComprehensionReport events={events} modality={view} detailed/>:null}
 {view==='vocabulary'&&<><p className="evidence-note">{student.active_days??'—'} of 7 days practiced. These recall results are independent of reading and listening comprehension.</p><div className="student-skills">{student.skills?.map(skill=>{const score=accuracy(skill.correct,skill.attempts),trend=skillTrend(skill);return <article key={skill.modality}><h3>{skillNames[skill.modality]??skill.modality}</h3><p className="student-score">{score===null?'Not tested':score+'%'}<small>{skill.correct} correct / {skill.attempts} attempts</small></p>{score!==null&&<progress aria-label={skillNames[skill.modality]+' accuracy'} value={score} max={100}/>}<dl><div><dt>Words practiced</dt><dd>{skill.words}</dd></div><div><dt>Missed at least twice</dt><dd>{skill.repeated_misses}</dd></div><div><dt>Recent change</dt><dd>{trend===null?'Insufficient evidence':(trend>0?'+':'')+trend+' pp'}</dd></div></dl><p>{evidenceAdvice(skill)}</p></article>;})}</div>{!student.skills&&<p>No detailed vocabulary evidence is available.</p>}<section className="report-panel" style={{marginTop:20}}><div className="report-panel-heading"><h3>Daily vocabulary recall</h3></div><ReportChart days={days} series={[{label:'Recall accuracy',values:(student.daily??[]).map(d=>accuracy(d.correct,d.attempts))}]} label={student.display_name+' daily vocabulary accuracy'}/></section></>}
 </div><details className="insight-method"><summary>Evidence, privacy & limitations</summary><p>All results cover seven UTC calendar days. Comprehension averages use AI-graded attempts only; self-ratings remain separate. Category scores use actual question-level grades, not duplicated overall scores. Replays and transcript use change task conditions, so supported and unsupported scores are not a causal comparison.</p><p>Vocabulary accuracy includes learning attempts and self-ratings. It is not long-term retention or an ILR proficiency score. Recent recall change compares three days with the preceding four, requiring five attempts in each. Private answers, passages, word lists, and notes are not exposed.</p></details></section>;
}
