'use client';
import {accuracy,evidenceAdvice,skillNames,skillTrend,type StudentReport} from '@/lib/student-report';
export default function StudentBreakdown({student,onClose}:{student:StudentReport;onClose?:()=>void}){
  return <section className="student-breakdown" aria-label={`${student.display_name} student breakdown`}>
    <header><div><p>LEARNER PROFILE · LAST 7 DAYS</p><h2>{student.display_name}</h2></div>{onClose?<button onClick={onClose}>Close details</button>:<span className="period-label">Individual progress</span>}</header>
    <div className="student-metrics"><p><strong>{student.reviews}</strong>Review attempts</p><p><strong>{student.active_days??'—'} / 7</strong>Days practiced</p><p><strong>{student.unique_words??'—'}</strong>Distinct words practiced</p></div>
    {!student.skills&&<p>Detailed reporting is not available yet. Summary results remain above.</p>}
    <div className="student-skills">{student.skills?.map(skill=>{const score=accuracy(skill.correct,skill.attempts),trend=skillTrend(skill);return <article key={skill.modality}><h3>{skillNames[skill.modality]??skill.modality}</h3><p className="student-score">{score===null?'Not tested':`${score}%`}<small>{skill.correct} correct / {skill.attempts} attempts</small></p>{score!==null&&<progress aria-label={`${skillNames[skill.modality]} accuracy`} value={score} max={100}/>}
      <dl><div><dt>Distinct words</dt><dd>{skill.words}</dd></div><div><dt>Words missed at least twice</dt><dd>{skill.repeated_misses}</dd></div><div><dt>Recent change</dt><dd>{trend===null?'Insufficient evidence':`${trend>0?'+':''}${trend} percentage points`}</dd></div></dl><p>{evidenceAdvice(skill)}</p></article>;})}</div>
    {!!student.daily?.length&&<section className="practice-chart"><div className="chart-heading"><h3>Practice rhythm</h3><span>Correct <i/> Missed</span></div><div className="practice-bars">{student.daily.map(day=><div className="practice-day" key={day.day}><div className="bar-space"><strong>{day.attempts}</strong><div className="practice-bar" style={{height:`${day.attempts/Math.max(1,...student.daily!.map(d=>d.attempts))*125}px`}}><i style={{height:`${day.attempts?day.correct/day.attempts*100:0}%`}}/></div></div><span>{new Date(`${day.day}T12:00:00Z`).toLocaleDateString('en-US',{weekday:'short',timeZone:'UTC'})}</span><small>{day.correct} correct</small></div>)}</div></section>}
    <details className="insight-method"><summary>How to read these results</summary><p className="muted">Recent change compares the last three UTC calendar days with the preceding four; both need at least five attempts. Accuracy includes learning attempts and self-rated answers—it is not a proficiency score or a measured long-term retention rate. Repeated words count once per skill.</p><p className="muted">Private notes, responses, and the learner’s word list are not exposed. Reading and listening comprehension are not measured by these vocabulary scores.</p></details>
  </section>;
}
