'use client';
import {useEffect,useState,useRef} from 'react';
import {getSupabaseClient} from '@/lib/supabase';
import {canManageClasses} from '@/lib/classroom-access';
type ClassRow={id:string;name:string;join_code:string};
import {classInviteLink,normalizeClassCode} from '@/lib/class-invites';
import {classroomCsv} from '@/lib/classroom-export';
import ClassroomInsights from '@/components/ClassroomInsights';
import type {StudentReport as Report} from '@/lib/student-report';
export default function Classroom(){
  const [teacher,setTeacher]=useState(false),[checked,setChecked]=useState(false);
  const [classes,setClasses]=useState<ClassRow[]>([]),[report,setReport]=useState<Report[]>([]),[selected,setSelected]=useState(''),[status,setStatus]=useState('Sign in on Cursos to manage or join a class.'),[busy,setBusy]=useState(false);
  const [memberships,setMemberships]=useState<{class_id:string;display_name:string;share_comprehension:boolean}[]>([]);
  const reportRequest=useRef(0);
  const refreshRequest=useRef(0);
  const [reportFailed,setReportFailed]=useState(false);
  const client=getSupabaseClient();
  async function refresh(){
    const request=++refreshRequest.current;
    if(!client){setChecked(true);return;}const {data:{user}}=await client.auth.getUser();if(request!==refreshRequest.current)return;setTeacher(canManageClasses(user));setChecked(true);if(!user){setClasses([]);setMemberships([]);setReport([]);return;}
    const [owned,membership]=await Promise.all([client.from('learning_classes').select('id,name,join_code').eq('owner_id',user.id).order('created_at'),client.from('learning_class_members').select('class_id,display_name,share_comprehension').eq('user_id',user.id)]);
    if(request!==refreshRequest.current)return;
    if(owned.error||membership.error){setStatus('Classrooms are awaiting database setup. Your existing study data is unchanged.');return;}
    setClasses(owned.data??[]);setMemberships(membership.data??[]);setStatus('Your classes are private. Only the class owner sees reports from students who join.');
  }
  useEffect(()=>{let active=true;void refresh();const subscription=client?.auth.onAuthStateChange(()=>{++refreshRequest.current;++reportRequest.current;setTeacher(false);setChecked(false);setClasses([]);setReport([]);setMemberships([]);setSelected('');setTimeout(()=>{if(active)void refresh();},0);});return()=>{active=false;++refreshRequest.current;++reportRequest.current;subscription?.data.subscription.unsubscribe();};},[]);
  async function showReport(id:string){if(!client)return;if(!id){++reportRequest.current;setSelected('');setReport([]);setBusy(false);setReportFailed(false);return;}const request=++reportRequest.current;setSelected(id);setBusy(true);setReportFailed(false);setReport([]);try{const [basic,comp]=await Promise.all([client.rpc('learning_class_report',{target:id}),client.rpc('learning_class_comprehension_report',{target:id})]);if(basic.error||comp.error)throw basic.error||comp.error;const data=(basic.data??[]).map((row:Report)=>({...row,...(comp.data??[]).find((item:Report)=>item.user_id===row.user_id)}));if(request!==reportRequest.current)return;setReport(data??[]);setStatus('Last seven UTC calendar days · vocabulary recall and opt-in comprehension, reported separately.');}catch{if(request!==reportRequest.current)return;setReportFailed(true);setStatus('The complete class report could not load. Retry or check your class access. No missing results have been replaced with zero.');}finally{if(request===reportRequest.current)setBusy(false);}}
  async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!client)return;const name=String(new FormData(event.currentTarget).get('name')||'').trim();setBusy(true);const {data,error}=await client.from('learning_classes').insert({name}).select('id').single();setBusy(false);if(error)setStatus('Could not create class. Sign in and try again.');else {await refresh();if(data)await showReport(data.id);}}
  async function join(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!client)return;const data=new FormData(event.currentTarget);setBusy(true);const {error}=await client.rpc('join_learning_class',{code:normalizeClassCode(String(data.get('code'))),learner_name:String(data.get('name')).trim()});setBusy(false);if(error)setStatus('Could not join. Check the class code and sign-in.');else await refresh();}
  async function shareComprehension(classId:string,enabled:boolean){if(!client)return;setBusy(true);const {error}=await client.rpc('learning_set_comprehension_sharing',{target:classId,enabled});setBusy(false);if(error)setStatus('Could not update comprehension sharing. Try again.');else await refresh();}
  async function copyInvite(code:string){const link=classInviteLink(window.location.origin,code);try{await navigator.clipboard.writeText(link);setStatus('Invite link copied. Send it privately to your friends.');}catch{setStatus('Could not copy automatically. Select and copy the invite link below.');}}
  function downloadReport(){if(!classroom||reportFailed||busy)return;const file=new Blob([classroomCsv(classroom.name,report)],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(file);const link=document.createElement('a');link.href=url;link.download='cursos-class-report-'+new Date().toISOString().slice(0,10)+'.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const classroom=classes.find(item=>item.id===selected);
  if(!teacher)return <main className="classroom-app"><a href="/#account">Back to my account</a><h1>My class membership</h1><p>{checked?'Join a class from My classes in your account. Only the designated teacher can create classes and view classroom reports.':'Checking your account…'}</p>{memberships.map(item=><section key={item.class_id}><h2>{item.display_name}</h2><label className="membership-sharing"><input type="checkbox" disabled={busy} checked={item.share_comprehension} onChange={e=>void shareComprehension(item.class_id,e.target.checked)}/>Share my reading/listening scores, question-type scores, times, rereads, replay counts, and transcript use with this class owner. No answers, passages, or private notes. Uncheck to stop sharing.</label><button disabled={busy} onClick={async()=>{if(!client||!confirm('Leave this class and stop sharing future reports?'))return;const {error}=await client.from('learning_class_members').delete().eq('class_id',item.class_id);if(error)setStatus('Could not leave. Try again.');else await refresh();}}>Leave class</button></section>)}<p role="status">{status}</p></main>;
  return <main className="classroom-app"><div className="insight-topbar"><a className="insight-brand" href="/">cursos <small>BY SYNAPTX</small></a><a href="/classroom/demo">Presentation demo ↗</a></div><header className="insight-page-heading"><div><p>BY SYNAPTX</p><h1>Classroom</h1><p>Targeted practice for a class—not one score for every skill.</p></div><a href="/classroom/demo">Presentation demo ↗</a></header><p className="classroom-status" role="status">{status}</p>
  <p className="evidence-note">Starting a pilot? <a href="/#account">Sign in or create your account ↗</a>, create a class below, then share its private invite link. Download a report each week; this dashboard shows the latest seven days, not the whole ten-week pilot.</p><details className="class-management"><summary>Create or join a class</summary><div className="classroom-controls"><form onSubmit={create}><h2>Teach a class</h2><label>Class name<input name="name" maxLength={100} required placeholder="Persian · Section 1"/></label><button disabled={busy}>Create class</button></form><form onSubmit={join}><h2>Join a class</h2><label>Class code<input name="code" required maxLength={24}/></label><label>Display name<input name="name" required maxLength={80} placeholder="Use an approved name or class alias"/></label><label className="consent"><input type="checkbox" required/>I agree to share my practice counts and separate text, audio, and pattern recall results with this class’s owner. Private notes and answers are not shared.</label><button disabled={busy}>Join class</button></form></div></details>
  <label>Your teaching classes<select value={selected} onChange={e=>void showReport(e.target.value)}><option value="">Choose a class…</option>{classes.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
  {classroom&&<section><div className="class-report-heading"><div><h2>{classroom.name}</h2><p>Class code: <code>{classroom.join_code}</code> · Share only with your students.</p><label className="class-invite-link">Private invite link<input readOnly aria-label="Private class invite link" value={classInviteLink('https://getcursos.vercel.app',classroom.join_code)} onFocus={e=>e.currentTarget.select()}/></label></div><div className="report-actions"><button onClick={()=>void copyInvite(classroom.join_code)}>Copy invite link</button><button disabled={busy||reportFailed||!report.length} onClick={downloadReport}>Download weekly report</button><button disabled={busy} onClick={()=>void showReport(selected)}>Refresh report</button></div></div>{busy?<p role="status">Loading class results…</p>:reportFailed?<p role="alert" className="empty-evidence">Report unavailable. Refresh to retry; this is not an empty class.</p>:<ClassroomInsights key={selected} students={report}/>}</section>}
  {!!memberships.length&&<section><h2>Classes you joined</h2>{memberships.map(item=><p key={item.class_id}>{item.display_name} · <button onClick={async()=>{if(!client||!confirm('Leave this class and stop sharing future reports?'))return;const {error}=await client.from('learning_class_members').delete().eq('class_id',item.class_id);if(error)setStatus('Could not leave. Try again.');else await refresh();}}>Leave class</button><label className="membership-sharing"><input type="checkbox" disabled={busy} checked={item.share_comprehension} onChange={e=>void shareComprehension(item.class_id,e.target.checked)}/>Share my last seven days of reading/listening scores, question-type scores, times, rereads, replay counts, and transcript use with this class owner. No answers or passages are shared. Uncheck to stop sharing.</label></p>)}</section>}
  <p className="muted">90% is a scheduling target, not a guaranteed outcome. This is an independent learning tool, not an official proficiency assessment. Use only institution-approved data.</p></main>;
}
