'use client';
import {useEffect,useState} from 'react';
import ClassroomOwnerGate from '@/components/ClassroomOwnerGate';
import {getSupabaseClient} from '@/lib/supabase';

type ClassRow={id:string;name:string};
type ReviewRow={id:string;created_at:string;modality:string;source_kind:string;register:string;latency_ms:number|null;release_status:string;issue_codes:string[];content_payload:{title?:string;textFa?:string;questions?:{question:string;referenceAnswer:string}[]};verdict?:string|null;reviewer_role?:string|null;blocking_issue?:string|null};

export default function ContentReview(){
 const [classes,setClasses]=useState<ClassRow[]>([]),[selected,setSelected]=useState(''),[rows,setRows]=useState<ReviewRow[]>([]),[status,setStatus]=useState('Choose a pilot class.'),[busy,setBusy]=useState(false);
 const client=getSupabaseClient();
 useEffect(()=>{if(!client)return;void client.from('learning_classes').select('id,name').order('created_at').then(({data})=>setClasses(data??[]));},[]);
 async function load(classId:string){setSelected(classId);setRows([]);if(!client||!classId)return;setBusy(true);const {data,error}=await client.rpc('content_review_queue',{target:classId,queue_limit:50});setRows(error?[]:data??[]);setStatus(error?'Review workflow is awaiting the pilot database update.':`${(data??[]).length} generated exercises available for review.`);setBusy(false);}
 async function save(event:React.FormEvent<HTMLFormElement>,runId:string){event.preventDefault();if(!client)return;const form=new FormData(event.currentTarget);setBusy(true);const {error}=await client.rpc('submit_content_human_review',{run_id:runId,role:String(form.get('role')),review_verdict:String(form.get('verdict')),natural:form.get('natural')==='on',accurate:form.get('accurate')==='on',useful:form.get('useful')==='on',usable:form.get('usable')==='on',issue:String(form.get('issue')||'')});setStatus(error?'Review could not be saved. Check your access and try again.':'Review saved. Automated QA and human review remain separate statuses.');setBusy(false);if(!error)await load(selected);}
 return <ClassroomOwnerGate><main className="classroom-app"><header className="insight-page-heading"><div><p>QUALITY / HUMAN REVIEW</p><h1>Persian generation review</h1><p>Native-speaker, instructor, or linguist judgment. Automated approval is not linguistic certification.</p></div></header><label>Pilot class<select value={selected} onChange={event=>void load(event.target.value)}><option value="">Choose a class…</option>{classes.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><p role="status">{busy?'Loading…':status}</p><div className="review-queue">{rows.map(row=><article className="report-panel" key={row.id}><div className="report-panel-heading"><h2>{row.content_payload?.title||'Generated exercise'}</h2><span>{row.modality} · {row.register} · {row.latency_ms??'—'}ms</span></div><p lang="fa" dir="rtl" className="review-persian">{row.content_payload?.textFa}</p><ol>{(row.content_payload?.questions??[]).map((question,index)=><li key={index}><b>{question.question}</b><br/><span>{question.referenceAnswer}</span></li>)}</ol><form className="human-review-form" onSubmit={event=>void save(event,row.id)}><label>Reviewer role<select name="role" defaultValue={row.reviewer_role??'instructor'}><option value="native_speaker">Native speaker</option><option value="instructor">Instructor</option><option value="linguist">Linguist</option></select></label><label>Verdict<select name="verdict" defaultValue={row.verdict??'accepted'}><option value="accepted">Accept</option><option value="minor_correction">Minor correction</option><option value="major_correction">Major correction</option><option value="rejected">Reject</option></select></label><label><input name="natural" type="checkbox"/>Natural Persian</label><label><input name="accurate" type="checkbox"/>Linguistically accurate</label><label><input name="useful" type="checkbox"/>Pedagogically useful</label><label><input name="usable" type="checkbox"/>Would use in instruction</label><label>Blocking issue<input name="issue" defaultValue={row.blocking_issue??''} maxLength={1000}/></label><button disabled={busy}>Save review</button></form></article>)}</div></main></ClassroomOwnerGate>;
}
