'use client';
import {useState} from 'react';
import StudentBreakdown from '@/components/StudentBreakdown';
import {accuracy,type StudentReport} from '@/lib/student-report';
const students:StudentReport[]=Array.from({length:16},(_,i)=>{
 const skillDays=['visual','audio','cloze'].map((modality,j)=>({modality,days:Array.from({length:7},(_,d)=>{const attempts=5+i+j+(d%3),correct=Math.round(attempts*(.60+((i+j*2)%7)*.045+d*.01));return {attempts,correct};})}));
 const skills=skillDays.map(({modality,days},j)=>{const attempts=days.reduce((sum,d)=>sum+d.attempts,0),correct=days.reduce((sum,d)=>sum+d.correct,0);return {modality,attempts,correct,words:20+i,repeated_misses:Math.min((i+j)%5,Math.floor((attempts-correct)/2)),early_attempts:days.slice(0,4).reduce((sum,d)=>sum+d.attempts,0),early_correct:days.slice(0,4).reduce((sum,d)=>sum+d.correct,0),recent_attempts:days.slice(4).reduce((sum,d)=>sum+d.attempts,0),recent_correct:days.slice(4).reduce((sum,d)=>sum+d.correct,0)};});
 const reviews=skills.reduce((sum,item)=>sum+item.attempts,0);
 const daily=Array.from({length:7},(_,d)=>{const day=new Date();day.setUTCDate(day.getUTCDate()-6+d);return {day:day.toISOString().slice(0,10),attempts:skillDays.reduce((sum,s)=>sum+s.days[d].attempts,0),correct:skillDays.reduce((sum,s)=>sum+s.days[d].correct,0)};});
 return {user_id:`demo-${i}`,display_name:`Student ${String(i+1).padStart(2,'0')}`,reviews,text_retention:accuracy(skills[0].correct,skills[0].attempts),audio_retention:accuracy(skills[1].correct,skills[1].attempts),pattern_retention:accuracy(skills[2].correct,skills[2].attempts),last_review:new Date().toISOString(),active_days:7,unique_words:20+i,skills,daily};
});
export default function ClassroomDemo(){const [selected,setSelected]=useState<StudentReport|null>(students[0]);return <main className="classroom-workspace"><a href="/classroom">← Real classrooms</a><header><div><p>DEMONSTRATION · SYNTHETIC DATA</p><h1>One class. Sixteen individual paths.</h1><p>Select a student to see the same breakdown available in live classrooms. These are invented examples, not learner results.</p></div></header><div className="student-demo-picker" aria-label="Sample students">{students.map(student=><button key={student.user_id} aria-pressed={selected?.user_id===student.user_id} onClick={()=>setSelected(student)}>{student.display_name}</button>)}</div>{selected&&<StudentBreakdown student={selected} onClose={()=>setSelected(null)}/>}<p><a href="https://synapt-x.vercel.app">Synaptx</a> · <a href="/">Cursos</a> · <a href="https://get-asl.vercel.app">Asl</a></p></main>;}
