export const dynamic = 'force-dynamic';
import ClassroomInsights from '@/components/ClassroomInsights';
import {accuracy,mean,type ComprehensionEvidence,type StudentReport} from '@/lib/student-report';
function demoStudents():StudentReport[]{return Array.from({length:16},(_,i)=>{
 const skillDays=['visual','audio','cloze'].map((modality,j)=>({modality,days:Array.from({length:7},(_,d)=>{const attempts=5+i+j+(d%3),correct=Math.round(attempts*(.60+((i+j*2)%7)*.045+d*.01));return {attempts,correct};})}));
 const skills=skillDays.map(({modality,days},j)=>{const attempts=days.reduce((sum,d)=>sum+d.attempts,0),correct=days.reduce((sum,d)=>sum+d.correct,0);return {modality,attempts,correct,words:20+i,repeated_misses:Math.min((i+j)%5,Math.floor((attempts-correct)/2)),early_attempts:days.slice(0,4).reduce((sum,d)=>sum+d.attempts,0),early_correct:days.slice(0,4).reduce((sum,d)=>sum+d.correct,0),recent_attempts:days.slice(4).reduce((sum,d)=>sum+d.attempts,0),recent_correct:days.slice(4).reduce((sum,d)=>sum+d.correct,0)};});
 const reviews=skills.reduce((sum,item)=>sum+item.attempts,0);
 const daily=Array.from({length:7},(_,d)=>{const day=new Date();day.setUTCDate(day.getUTCDate()-6+d);return {day:day.toISOString().slice(0,10),attempts:skillDays.reduce((sum,s)=>sum+s.days[d].attempts,0),correct:skillDays.reduce((sum,s)=>sum+s.days[d].correct,0)};});
 const comprehension:ComprehensionEvidence[]=daily.flatMap((day,d)=>(['reading','listening'] as const).map((modality,j)=>{const questions=(['main_idea','detail','detail','inference','discourse'] as const).map((type,q)=>({type,score:Math.min(100,Math.max(20,62+(i*3%21)+[0,8,3,-6,7,4,-2][d]-j*8-q*3))}));return {id:`sample-${i}-${d}-${j}`,modality,practice_mode:'full',attempted_at:day.day+'T10:00:00Z',score:mean(questions.map(q=>q.score)),grading_mode:d===2&&i%3===0?'self':'ai',listens:modality==='listening'?1+(i+d)%3:null,transcript:modality==='listening'?(i+d)%5===0:null,rereads:modality==='reading'?(i+d)%3:null,duration_ms:modality==='reading'?(180+i*5+d*9)*1000:null,questions};}));
 return {user_id:`demo-${i}`,display_name:`Student ${String(i+1).padStart(2,'0')}`,reviews,text_retention:accuracy(skills[0].correct,skills[0].attempts),audio_retention:accuracy(skills[1].correct,skills[1].attempts),pattern_retention:accuracy(skills[2].correct,skills[2].attempts),last_review:new Date().toISOString(),active_days:7,unique_words:20+i,skills,daily,comprehension_shared:true,comprehension};
});}
export default function ClassroomDemo(){const students=demoStudents();return <main className="classroom-app"><div className="insight-topbar"><a className="insight-brand" href="/">cursos <small>BY SYNAPTX</small></a><nav className="insight-nav"><a href="/">Study</a><a href="https://get-asl.vercel.app">Asl ↗</a><a href="/classroom">My classrooms ↗</a></nav></div><header className="insight-page-heading"><div><p>CLASSROOM / INSIGHTS</p><h1>Persian · Class overview</h1></div><span className="insight-period">Last 7 days · UTC</span></header><p className="demo-disclosure"><span>PRESENTATION DEMO</span>16 sample learners. All results are synthetic.</p><ClassroomInsights students={students}/></main>;}
